{
 "title": "Metric Practice Dashboard",
 "time": { "from": "2022-02-01T05:00:00.000Z", "to": "2022-03-01T05:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number Missing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values AS \"value\", \"timestamp\" AS \"time\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns AS \"value\", \"timestamp\" AS \"time\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}