[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable=["missing-function-docstring",
        "missing-final-newline",
        "missing-class-docstring",
        "too-few-public-methods",
        "missing-module-docstring"
]